spring:
  application:
    name: eureka-dummy-service


server:
  port: 8081


eureka:
  instance:
    eureka.instance.preferIpAddress=true
    eureka.instance.lease-renewal-interval-in-seconds=30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  
    